FROM continuumio/anaconda3:2020.02

WORKDIR /tmp/Notebooks

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils
RUN python -m pip install --upgrade pip

RUN mkdir /tmp/Notebooks/.utils
ADD install_latest.py /tmp/Notebooks/.utils/install_latest.py

# Install JupyterLab Git extension
# ------------------------
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
RUN curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN apt-get update
RUN apt-get install -y yarn
RUN python -m pip install --upgrade jupyterlab-git
RUN jupyter lab build

# Install java 8
# -----------------------
RUN apt-get install -y apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common
RUN wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
RUN add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
RUN mkdir -p /usr/share/man/man1
RUN apt-get update
RUN apt-get install -y adoptopenjdk-8-hotspot
RUN apt-get install -y ca-certificates-java && update-ca-certificates -f
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
RUN apt-get clean

# Install latest version of ProActive library
# ------------------------
RUN python /tmp/Notebooks/.utils/install_latest.py proactive

RUN apt-get install -y build-essential
RUN apt-get install -y manpages-dev

# Install Graphviz
# ------------------------
RUN apt-get clean all
RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install -y --fix-missing graphviz-dev
RUN conda install -y graphviz

# Install latest version of ProActive Jupyter Kernel
# ------------------------
RUN python /tmp/Notebooks/.utils/install_latest.py proactive-jupyter-kernel
RUN python -m proactive-jupyter-kernel.install

# Install Bash Kernel
# ------------------------
RUN pip install bash_kernel
RUN python -m bash_kernel.install

# Install BeakerX Kernels
# ------------------------
RUN pip install beakerx
RUN beakerx install

# Copying resources
# ------------------------
# http://jupyter-notebook.readthedocs.io/en/stable/security.html
RUN git clone https://github.com/ow2-proactive/proactive-jupyter-notebooks.git

EXPOSE 8888

ENV JUPYTERLAB_TOKEN=''

ENTRYPOINT jupyter lab --port=8888 --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=$JUPYTERLAB_TOKEN --NotebookApp.password=''