# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dlaas.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dlaas.proto',
  package='dlaas',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x64laas.proto\x12\x05\x64laas\"\xba\x01\n\x0bModelConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tbase_path\x18\x02 \x01(\t\x12\x16\n\x0emodel_platform\x18\x03 \x01(\t\x12>\n\x14model_version_policy\x18\x04 \x03(\x0b\x32 .dlaas.ModelConfig.Versionpolicy\x1a\x32\n\rVersionpolicy\x12!\n\x08specific\x18\x66 \x03(\x0b\x32\x0f.dlaas.Specific\"5\n\x0fModelConfigList\x12\"\n\x06\x63onfig\x18\x01 \x03(\x0b\x32\x12.dlaas.ModelConfig\"?\n\nFileConfig\x12\x31\n\x11model_config_list\x18\x01 \x03(\x0b\x32\x16.dlaas.ModelConfigList\"\x1c\n\x08Specific\x12\x10\n\x08versions\x18\x01 \x03(\x03\x62\x06proto3'
)




_MODELCONFIG_VERSIONPOLICY = _descriptor.Descriptor(
  name='Versionpolicy',
  full_name='dlaas.ModelConfig.Versionpolicy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='specific', full_name='dlaas.ModelConfig.Versionpolicy.specific', index=0,
      number=102, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=209,
)

_MODELCONFIG = _descriptor.Descriptor(
  name='ModelConfig',
  full_name='dlaas.ModelConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dlaas.ModelConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_path', full_name='dlaas.ModelConfig.base_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_platform', full_name='dlaas.ModelConfig.model_platform', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model_version_policy', full_name='dlaas.ModelConfig.model_version_policy', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MODELCONFIG_VERSIONPOLICY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=209,
)


_MODELCONFIGLIST = _descriptor.Descriptor(
  name='ModelConfigList',
  full_name='dlaas.ModelConfigList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='dlaas.ModelConfigList.config', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=264,
)


_FILECONFIG = _descriptor.Descriptor(
  name='FileConfig',
  full_name='dlaas.FileConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_config_list', full_name='dlaas.FileConfig.model_config_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=329,
)


_SPECIFIC = _descriptor.Descriptor(
  name='Specific',
  full_name='dlaas.Specific',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='versions', full_name='dlaas.Specific.versions', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=359,
)

_MODELCONFIG_VERSIONPOLICY.fields_by_name['specific'].message_type = _SPECIFIC
_MODELCONFIG_VERSIONPOLICY.containing_type = _MODELCONFIG
_MODELCONFIG.fields_by_name['model_version_policy'].message_type = _MODELCONFIG_VERSIONPOLICY
_MODELCONFIGLIST.fields_by_name['config'].message_type = _MODELCONFIG
_FILECONFIG.fields_by_name['model_config_list'].message_type = _MODELCONFIGLIST
DESCRIPTOR.message_types_by_name['ModelConfig'] = _MODELCONFIG
DESCRIPTOR.message_types_by_name['ModelConfigList'] = _MODELCONFIGLIST
DESCRIPTOR.message_types_by_name['FileConfig'] = _FILECONFIG
DESCRIPTOR.message_types_by_name['Specific'] = _SPECIFIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelConfig = _reflection.GeneratedProtocolMessageType('ModelConfig', (_message.Message,), {

  'Versionpolicy' : _reflection.GeneratedProtocolMessageType('Versionpolicy', (_message.Message,), {
    'DESCRIPTOR' : _MODELCONFIG_VERSIONPOLICY,
    '__module__' : 'dlaas_pb2'
    # @@protoc_insertion_point(class_scope:dlaas.ModelConfig.Versionpolicy)
    })
  ,
  'DESCRIPTOR' : _MODELCONFIG,
  '__module__' : 'dlaas_pb2'
  # @@protoc_insertion_point(class_scope:dlaas.ModelConfig)
  })
_sym_db.RegisterMessage(ModelConfig)
_sym_db.RegisterMessage(ModelConfig.Versionpolicy)

ModelConfigList = _reflection.GeneratedProtocolMessageType('ModelConfigList', (_message.Message,), {
  'DESCRIPTOR' : _MODELCONFIGLIST,
  '__module__' : 'dlaas_pb2'
  # @@protoc_insertion_point(class_scope:dlaas.ModelConfigList)
  })
_sym_db.RegisterMessage(ModelConfigList)

FileConfig = _reflection.GeneratedProtocolMessageType('FileConfig', (_message.Message,), {
  'DESCRIPTOR' : _FILECONFIG,
  '__module__' : 'dlaas_pb2'
  # @@protoc_insertion_point(class_scope:dlaas.FileConfig)
  })
_sym_db.RegisterMessage(FileConfig)

Specific = _reflection.GeneratedProtocolMessageType('Specific', (_message.Message,), {
  'DESCRIPTOR' : _SPECIFIC,
  '__module__' : 'dlaas_pb2'
  # @@protoc_insertion_point(class_scope:dlaas.Specific)
  })
_sym_db.RegisterMessage(Specific)


# @@protoc_insertion_point(module_scope)
